/**
 * MCM Workspace Seed — Massage Chairs and More
 *
 * This file contains the default workspace configuration for the MCM brand.
 * All MCM-specific data (personas, topics, brand positioning) lives HERE,
 * scoped to the MCM workspace only. Nothing in this file is global.
 */

import type { SEOWorkspace, WorkspacePersona, WorkspaceContentTopic, PlatformConfig } from '../workspaceTypes';
import { ALL_PLATFORMS } from '../workspaceTypes';

// ─── MCM Workspace ID (stable so we can check if it already exists) ──────────

export const MCM_WORKSPACE_ID = 'mcm-default';

// ─── MCM Personas ────────────────────────────────────────────────────────────

export const MCM_PERSONAS: WorkspacePersona[] = [
  {
    id: 'mcm-p01',
    name: 'Local Demo Seeker',
    shortDescription: 'Actively searching for a nearby showroom to test massage chairs in person before buying.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Book a demo',
    claimRiskLevel: 'low',
    recommendedTone: 'Welcoming, informative, low-pressure',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p02',
    name: 'Final-Decision Comparer',
    shortDescription: 'Has narrowed down to 2–3 models. Needs side-by-side comparison and expert validation to commit.',
    intentStages: ['decision'],
    defaultCTA: 'Compare chairs in person',
    claimRiskLevel: 'low',
    recommendedTone: 'Expert, precise, data-driven',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p03',
    name: 'Online-Price Cross-Shopper',
    shortDescription: 'Comparing prices across Amazon, Costco, and brand sites. Needs to understand why showroom value justifies the price.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Call for expert guidance',
    claimRiskLevel: 'low',
    recommendedTone: 'Transparent, value-focused, non-defensive',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p04',
    name: 'Fit & Space Certainty Buyer',
    shortDescription: 'Worried about chair dimensions, room fit, doorway clearance, and wall clearance. Needs spatial confidence.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Check delivery/space fit',
    claimRiskLevel: 'low',
    recommendedTone: 'Practical, detail-oriented, reassuring',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p05',
    name: 'Warranty & Service Confidence Buyer',
    shortDescription: 'Concerned about what happens after purchase — warranty coverage, parts, labor, local service availability.',
    intentStages: ['decision'],
    defaultCTA: 'Ask about warranty/service',
    claimRiskLevel: 'low',
    recommendedTone: 'Trust-building, transparent, specific',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p06',
    name: 'Spouse / Household Approval Buyer',
    shortDescription: 'Interested but needs to justify the purchase to a partner or household. Needs ROI and lifestyle framing.',
    intentStages: ['consideration'],
    defaultCTA: 'Visit showroom together',
    claimRiskLevel: 'low',
    recommendedTone: 'Relatable, practical, value-proving',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p07',
    name: 'Pain & Tension Comfort Seeker',
    shortDescription: 'Motivated by back pain, neck tension, or daily stress. Seeking relief at home without ongoing massage appointments.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Book a demo',
    claimRiskLevel: 'high',
    recommendedTone: 'Empathetic, wellness-focused, compliance-safe',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p08',
    name: 'Practical Premium Value Buyer',
    shortDescription: 'Wants the best value in the $3K–$6K range. Quality matters but not interested in paying flagship prices.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Compare models',
    claimRiskLevel: 'low',
    recommendedTone: 'Honest, value-driven, comparison-focused',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p09',
    name: 'Premium Wellness Executive',
    shortDescription: 'High-income professional investing in personal wellness. Sees a massage chair as part of a premium self-care routine.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'medium',
    recommendedTone: 'Premium, refined, results-oriented',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p10',
    name: 'Luxury Home Design Buyer',
    shortDescription: 'Buying a massage chair as a design piece for a home theater, living room, or dedicated wellness space. Aesthetics are critical.',
    intentStages: ['consideration'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Design-forward, aspirational, curated',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p11',
    name: 'High-Income Empty Nester',
    shortDescription: 'Kids have left home. Investing in comfort and lifestyle upgrades. Has the budget and space for a premium chair.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Book a demo',
    claimRiskLevel: 'medium',
    recommendedTone: 'Warm, lifestyle-focused, premium',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p12',
    name: 'Home Office Decompression Buyer',
    shortDescription: 'Remote/hybrid worker dealing with desk fatigue. Wants a daily recovery tool, not a luxury splurge.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Compare models',
    claimRiskLevel: 'medium',
    recommendedTone: 'Practical, productivity-aware, relatable',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p13',
    name: 'Panasonic Engineering Trust Buyer',
    shortDescription: 'Specifically interested in Panasonic/Japanese-engineered chairs. Values precision engineering, brand heritage, and reliability.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Technical, brand-respectful, heritage-aware',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p14',
    name: 'OHCO Craftsmanship & Escape Buyer',
    shortDescription: 'Drawn to OHCO\'s artisan design, immersive experience, and escape-pod aesthetic. Willing to invest at flagship level.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Artisan, experiential, premium storytelling',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p15',
    name: 'Positive Posture Feature-Value Buyer',
    shortDescription: 'Exploring Positive Posture chairs for their clinical focus, customizable programs, and mid-to-high value positioning.',
    intentStages: ['consideration'],
    defaultCTA: 'Compare models',
    claimRiskLevel: 'medium',
    recommendedTone: 'Feature-focused, practical, wellness-aware',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p16',
    name: 'D.Core Quiet Luxury Buyer',
    shortDescription: 'Attracted to D.Core\'s modern design language, quiet operation, and understated luxury positioning.',
    intentStages: ['consideration'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Minimal, design-conscious, modern',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p17',
    name: 'KOYO Japanese Value-Premium Buyer',
    shortDescription: 'Interested in KOYO for Japanese quality at a more accessible premium price point. Values craftsmanship without flagship pricing.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Compare models',
    claimRiskLevel: 'low',
    recommendedTone: 'Heritage-aware, value-conscious, quality-focused',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p18',
    name: 'Recovery-Focused Athlete',
    shortDescription: 'Uses massage for post-workout recovery, muscle soreness, and performance optimization. Interested in deep tissue and stretching features.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Book a demo',
    claimRiskLevel: 'high',
    recommendedTone: 'Performance-oriented, evidence-aware, compliance-safe',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p19',
    name: 'Senior Comfort & Safety Planner',
    shortDescription: 'Buying for a senior family member or themselves. Prioritizes ease of use, gentle modes, safe entry/exit, and simple controls.',
    intentStages: ['consideration', 'decision'],
    defaultCTA: 'Call for expert guidance',
    claimRiskLevel: 'high',
    recommendedTone: 'Caring, accessibility-focused, patient',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p20',
    name: 'Gift-for-Parent / Family Wellness Buyer',
    shortDescription: 'Buying a massage chair as a gift for a parent, spouse, or family member. Needs help choosing without the recipient testing.',
    intentStages: ['consideration'],
    defaultCTA: 'Call for expert guidance',
    claimRiskLevel: 'low',
    recommendedTone: 'Warm, helpful, gift-framing',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p21',
    name: 'AI / Advanced Technology Explorer',
    shortDescription: 'Excited by AI body scanning, voice control, app integration, and cutting-edge massage technology. Early adopter mindset.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Tech-forward, innovative, feature-rich',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p22',
    name: 'First-Time Massage Chair Buyer',
    shortDescription: 'Has never owned a massage chair. Overwhelmed by options and price ranges. Needs confidence and education.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Visit showroom',
    claimRiskLevel: 'low',
    recommendedTone: 'Educational, patient, trust-building',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p23',
    name: 'Foot / Calf Relief Seeker',
    shortDescription: 'Specifically interested in foot and calf massage features — foot rollers, air compression, reflexology. May also consider standalone foot massagers.',
    intentStages: ['awareness', 'consideration'],
    defaultCTA: 'Compare models',
    claimRiskLevel: 'medium',
    recommendedTone: 'Specific, feature-focused, comfort-framing',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p24',
    name: 'Compact Home / Apartment Buyer',
    shortDescription: 'Lives in a smaller home, apartment, or condo. Needs a space-efficient chair that doesn\'t dominate the room.',
    intentStages: ['consideration'],
    defaultCTA: 'Check delivery/space fit',
    claimRiskLevel: 'low',
    recommendedTone: 'Practical, space-aware, solution-oriented',
    allowedTopicIds: [],
  },
  {
    id: 'mcm-p25',
    name: 'Post-Demo Follow-Up Buyer',
    shortDescription: 'Has already visited the showroom and tested chairs. Now researching online before making a final decision.',
    intentStages: ['decision'],
    defaultCTA: 'Call for expert guidance',
    claimRiskLevel: 'low',
    recommendedTone: 'Confident, closing-ready, recap-focused',
    allowedTopicIds: [],
  },
];

// ─── MCM Content Topics ──────────────────────────────────────────────────────

export const MCM_CONTENT_TOPICS: WorkspaceContentTopic[] = [
  {
    id: 'mcm-t1',
    topic: 'Best Massage Chairs of 2025 — Comparison Guide',
    category: 'Comparison',
    description: 'Comprehensive comparison of top massage chair brands and models available in 2025. Compare Osaki, Luraco, Titan, OHCO, Infinity, Daiwa, and more.',
    targetPersonaIds: ['mcm-p1', 'mcm-p2'],
    suggestedKeywords: ['best massage chairs 2025', 'massage chair comparison', 'top massage chair brands'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'middle',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'mcm-t2',
    topic: 'How to Choose the Right Massage Chair for Your Body',
    category: 'Buyer Guide',
    description: 'Guide on matching chair features (track type, roller width, body scan, intensity) to different body types — height, weight, build.',
    targetPersonaIds: ['mcm-p1', 'mcm-p4', 'mcm-p6'],
    suggestedKeywords: ['how to choose massage chair', 'massage chair for tall person', 'massage chair body type guide'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'middle',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'mcm-t3',
    topic: 'Your First Showroom Visit — What to Expect',
    category: 'Showroom Experience',
    description: 'Walk potential customers through what happens at an MCM showroom visit. Reduce anxiety, build trust, explain the demo process.',
    targetPersonaIds: ['mcm-p1', 'mcm-p3', 'mcm-p6'],
    suggestedKeywords: ['massage chair showroom near me', 'massage chair demo', 'try massage chair before buying'],
    contentFormats: ['blog', 'landing-page'],
    funnelStage: 'bottom',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'mcm-t4',
    topic: '4D vs 3D vs 2D Massage Chairs — What\'s the Difference?',
    category: 'Technology Explainer',
    description: 'Explain the differences between 2D, 3D, and 4D massage technology in plain language. Help buyers understand what they\'re paying for.',
    targetPersonaIds: ['mcm-p1', 'mcm-p2', 'mcm-p8'],
    suggestedKeywords: ['4D massage chair', '3D vs 4D massage chair', 'massage chair technology explained'],
    contentFormats: ['blog'],
    funnelStage: 'top',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t5',
    topic: 'Zero Gravity Massage Chairs — Benefits and Best Models',
    category: 'Feature Deep-Dive',
    description: 'Explain zero gravity positioning, its benefits for spinal decompression and circulation, and which MCM-carried models offer the best zero gravity experience.',
    targetPersonaIds: ['mcm-p1', 'mcm-p4', 'mcm-p6'],
    suggestedKeywords: ['zero gravity massage chair', 'zero gravity recliner benefits', 'best zero gravity massage chair'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'top',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t6',
    topic: 'Massage Chair Delivery, Installation, and Space Planning',
    category: 'Purchase Logistics',
    description: 'Address common delivery anxieties: room dimensions, doorway width, electrical requirements, white-glove delivery vs self-setup.',
    targetPersonaIds: ['mcm-p1', 'mcm-p5', 'mcm-p7'],
    suggestedKeywords: ['massage chair delivery', 'massage chair room size', 'massage chair installation'],
    contentFormats: ['blog'],
    funnelStage: 'bottom',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t7',
    topic: 'Massage Chair Warranty and Service — What to Look For',
    category: 'Trust Building',
    description: 'Explain warranty tiers, parts vs labor coverage, service network, and why local service matters for a $3K–$10K purchase.',
    targetPersonaIds: ['mcm-p1', 'mcm-p2', 'mcm-p6'],
    suggestedKeywords: ['massage chair warranty', 'massage chair service', 'massage chair extended warranty'],
    contentFormats: ['blog'],
    funnelStage: 'bottom',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t8',
    topic: 'Massage Chair Gift Guide — How to Buy for Someone Else',
    category: 'Gift Buying',
    description: 'Guide for gift buyers on how to choose the right chair for a spouse, parent, or family member without them being present to test.',
    targetPersonaIds: ['mcm-p3'],
    suggestedKeywords: ['massage chair gift', 'massage chair for parents', 'luxury gift ideas'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'middle',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t9',
    topic: 'Massage Chair vs Massage Therapist — Cost and Convenience',
    category: 'Value Proposition',
    description: 'Compare the long-term cost of regular massage therapy appointments vs a one-time massage chair investment. Frame the ROI argument.',
    targetPersonaIds: ['mcm-p4', 'mcm-p8'],
    suggestedKeywords: ['massage chair vs therapist', 'massage chair cost comparison', 'massage chair ROI'],
    contentFormats: ['blog'],
    funnelStage: 'top',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'mcm-t10',
    topic: 'Setting Up a Massage Chair in Your Home Office',
    category: 'Lifestyle',
    description: 'Guide for remote workers on incorporating a massage chair into a home office or adjacent recovery space. Focus on compact models and daily micro-recovery.',
    targetPersonaIds: ['mcm-p8'],
    suggestedKeywords: ['massage chair home office', 'compact massage chair', 'massage chair for remote workers'],
    contentFormats: ['blog'],
    funnelStage: 'middle',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'mcm-t11',
    topic: 'Best Massage Chairs for Couples — Dual Setup Guide',
    category: 'Lifestyle',
    description: 'Guide for couples considering two chairs: room planning, matching vs different models, multi-user profiles, and shared wellness routines.',
    targetPersonaIds: ['mcm-p7'],
    suggestedKeywords: ['massage chair for couples', 'dual massage chair setup', 'his and hers massage chairs'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'middle',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'mcm-t12',
    topic: 'Premium vs Mid-Range Massage Chairs — Is Flagship Worth It?',
    category: 'Comparison',
    description: 'Help buyers decide between a $3K–$5K mid-range chair and a $7K–$12K flagship. What do you actually get for the extra money?',
    targetPersonaIds: ['mcm-p1', 'mcm-p2', 'mcm-p5'],
    suggestedKeywords: ['expensive massage chair worth it', 'luxury massage chair', 'premium vs budget massage chair'],
    contentFormats: ['blog', 'comparison-page'],
    funnelStage: 'middle',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'mcm-t13',
    topic: 'Massage Chairs for Seniors — Accessibility and Comfort Guide',
    category: 'Audience-Specific',
    description: 'Guide specifically for elderly users or their adult children. Focus on easy entry/exit, gentle modes, simple controls, and safety features.',
    targetPersonaIds: ['mcm-p6'],
    suggestedKeywords: ['massage chair for elderly', 'easy to use massage chair', 'gentle massage chair for seniors'],
    contentFormats: ['blog', 'guide'],
    funnelStage: 'middle',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'mcm-t14',
    topic: 'Heated Massage Chairs — How Heat Therapy Enhances Your Massage',
    category: 'Feature Deep-Dive',
    description: 'Explain how heat therapy works in massage chairs, which models have the best heat features, and how heated rollers differ from heated pads.',
    targetPersonaIds: ['mcm-p4', 'mcm-p6'],
    suggestedKeywords: ['heated massage chair', 'massage chair with heat', 'heat therapy massage chair'],
    contentFormats: ['blog'],
    funnelStage: 'top',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'mcm-t15',
    topic: 'Brand Spotlight — Osaki, Luraco, OHCO, Titan, Infinity, Daiwa',
    category: 'Brand Guide',
    description: 'Individual brand profile pages explaining each brand\'s strengths, price range, signature models, and who each brand is best suited for.',
    targetPersonaIds: ['mcm-p1', 'mcm-p2'],
    suggestedKeywords: ['Osaki massage chair review', 'Luraco massage chair', 'best Titan massage chair'],
    contentFormats: ['blog', 'landing-page'],
    funnelStage: 'middle',
    priority: 'high',
    status: 'planned',
  },
];

// ─── MCM Platform Configuration ──────────────────────────────────────────────

function mcmPlatforms(): PlatformConfig[] {
  const enabled = new Set(['website-blog', 'landing-page', 'shopify-page', 'instagram', 'facebook', 'youtube', 'google-business']);
  return ALL_PLATFORMS.map((p) => ({ platform: p, enabled: enabled.has(p) }));
}

// ─── MCM Workspace Seed ──────────────────────────────────────────────────────

export function buildMCMWorkspace(): Omit<SEOWorkspace, 'createdAt' | 'updatedAt'> {
  return {
    id: MCM_WORKSPACE_ID,

    // Brand Identity
    clientName: 'Massage Chairs and More',
    brandName: 'Massage Chairs and More',
    websiteUrl: 'https://www.massagechairsandmore.com/',
    industry: 'Premium massage chairs, home wellness, luxury relaxation, recovery, showroom retail',
    businessType: 'B2C',
    targetCountries: ['United States'],
    targetMarket: 'California / Bay Area / NorCal high-ticket buyers researching massage chairs, local showroom demos, premium massage chair comparisons, luxury home wellness, recovery, comfort, and purchase-risk reduction.',

    // Voice & Style
    toneOfVoice: 'Clear, premium, expert, calm, practical, trust-building, non-pushy',
    articleStyle: 'Expert guide style — structured, scannable, comparison-heavy, FAQ-rich, showroom-action-oriented',

    // Business
    coreOffer: 'Premium massage chairs from multiple top brands, in-person showroom comparison and demo experience, expert guidance for high-ticket purchase decisions',
    conversionGoals: 'Showroom visits, demo bookings, phone consultations, direct purchases',
    primaryCTA: 'Visit showroom | Book a demo | Compare chairs in person | Call for expert guidance | Check delivery/space fit | Ask about warranty/service | Compare models',
    brandDifferentiators: [
      'Multi-brand comparison under one roof',
      'Premium in-person showroom experience',
      'Expert guidance instead of pressure selling',
      'Ability to test/demo chairs before buying',
      'Risk reduction around fit, space, delivery, installation, service, and warranty',
      'Strong local showroom presence in California / Bay Area / NorCal',
      'High-ticket purchase confidence',
      'Matching the right chair to the customer\'s body, home, budget, and wellness goals',
    ].join(' · '),
    complianceNotes: [
      'Avoid medical claims — do not say massage chairs cure, treat, fix, heal, or eliminate medical conditions.',
      'Use safer wording: relaxation, comfort, daily recovery routine, stress reset, muscle tension relief, better rest routine, wellness support, purchase confidence.',
      'For health-sensitive content, suggest consulting a physician where appropriate.',
    ].join('\n'),

    // Keywords — empty until uploaded
    keywordList: [],
    keywordListUploadedAt: null,
    keywordListVersion: 0,

    // Sitemap
    sitemapUrl: 'https://www.massagechairsandmore.com/sitemap.xml',
    sitemapLastCheckedAt: null,
    sitemapPages: [],

    // Assets
    assets: [],

    // Platforms
    platforms: mcmPlatforms(),

    // Libraries
    personas: MCM_PERSONAS,
    contentTopics: MCM_CONTENT_TOPICS,

    // Content
    projectIds: [],
    contentEntries: [],
  };
}
